version: '3.8'

services:
  alert_price:
    build: .
    image: alert_price:latest
    restart: always
    env_file:
      - .env
    ports:
      - "8088:8088"
    environment:
      REDIS_HOST: "localhost"
      REDIS_PORT: 6379
    depends_on: []
