version: '3.8'

services:
  alert_price:
    build: .
    image: alert_price:latest
    restart: always
    env_file:
      - .env
    ports:
      - "8088:8088"
    environment:
      REDIS_HOST: "alert_price_redis"  # имя контейнера Redis
      REDIS_PORT: 6379
    networks:
      - skynet

networks:
  skynet:
    external: true
